### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by iamsjunaid** [ShaliniNayan/Capstone-Project-Conference-page#1]
### Issues found 🔴: 

1. Remove comments from the stylesheet as it will take unnecessary storage space. 
2. Add subtitle for the speakers in the speaker section dynamically using javascript.

**Comment by berylcl** [comment]
:white_check_mark: The paragrah "A joyful celebration ..." should be aligned left 
:white_check_mark:the programs should have less margin bertween them.
:white_check_mark:the see whole program button should be centered.

**Comment by ShaliniNayan** [comment]
Thank you and noted.
